@@startuml

ActivityThread -> Activity: performDestroyActivity(r.activity.retainNonConfigurationInstances)   
Activity -> ComponentActivity: onRetainNonConfigurationInstance()     

newpage

ActivityThread -> Activity: performLaunchActivity(activity.attach)  
Activity -> ComponentActivity: getLastNonConfigurationInstance


@@enduml